
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.DatiClient;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoBruciaturaPunti;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoCaricamentoPunti;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoGenerazioneBuono;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoSaldoPunti;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoStornoScontrino;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoTagliBuono;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoUtilizzoBuono;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoVerificaBuono;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.Scontrino;
import org.datacontract.schemas._2004._07.expert_loyalty_ws.VerificaCodice;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILoyaltyIntegration", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.expert_loyalty_domain.ObjectFactory.class,
    org.datacontract.schemas._2004._07.expert_loyalty_domain_services_dto.ObjectFactory.class,
    org.datacontract.schemas._2004._07.expert_loyalty_ws.ObjectFactory.class,
    org.datacontract.schemas._2004._07.shield.ObjectFactory.class,
    org.shield_services.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ILoyaltyIntegration {


    /**
     * 
     * @param datiClient
     * @param scontrino
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoCaricamentoPunti
     */
    @WebMethod(operationName = "CaricamentoPunti", action = "http://tempuri.org/ILoyaltyIntegration/CaricamentoPunti")
    @WebResult(name = "CaricamentoPuntiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CaricamentoPunti", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CaricamentoPunti")
    @ResponseWrapper(localName = "CaricamentoPuntiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CaricamentoPuntiResponse")
    public RisultatoCaricamentoPunti caricamentoPunti(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "scontrino", targetNamespace = "http://tempuri.org/")
        Scontrino scontrino);

    /**
     * 
     * @param datiClient
     * @param idTransazione
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoStornoScontrino
     */
    @WebMethod(operationName = "StornoScontrino", action = "http://tempuri.org/ILoyaltyIntegration/StornoScontrino")
    @WebResult(name = "StornoScontrinoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StornoScontrino", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StornoScontrino")
    @ResponseWrapper(localName = "StornoScontrinoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StornoScontrinoResponse")
    public RisultatoStornoScontrino stornoScontrino(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "idTransazione", targetNamespace = "http://tempuri.org/")
        String idTransazione);

    /**
     * 
     * @param datiClient
     * @param codiceCard
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoSaldoPunti
     */
    @WebMethod(operationName = "SaldoPunti", action = "http://tempuri.org/ILoyaltyIntegration/SaldoPunti")
    @WebResult(name = "SaldoPuntiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaldoPunti", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaldoPunti")
    @ResponseWrapper(localName = "SaldoPuntiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaldoPuntiResponse")
    public RisultatoSaldoPunti saldoPunti(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "codiceCard", targetNamespace = "http://tempuri.org/")
        String codiceCard);

    /**
     * 
     * @param verificaCodice
     * @param datiClient
     * @param totaleSpesa
     * @param puntiRichiesti
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoBruciaturaPunti
     */
    @WebMethod(operationName = "BruciaturaPunti", action = "http://tempuri.org/ILoyaltyIntegration/BruciaturaPunti")
    @WebResult(name = "BruciaturaPuntiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BruciaturaPunti", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BruciaturaPunti")
    @ResponseWrapper(localName = "BruciaturaPuntiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BruciaturaPuntiResponse")
    public RisultatoBruciaturaPunti bruciaturaPunti(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "verificaCodice", targetNamespace = "http://tempuri.org/")
        VerificaCodice verificaCodice,
        @WebParam(name = "puntiRichiesti", targetNamespace = "http://tempuri.org/")
        Integer puntiRichiesti,
        @WebParam(name = "totaleSpesa", targetNamespace = "http://tempuri.org/")
        String totaleSpesa);

    /**
     * 
     * @param verificaCodice
     * @param datiClient
     * @param puntiRichiesti
     * @param valoreRichiesto
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoGenerazioneBuono
     */
    @WebMethod(operationName = "GenerazioneBuono", action = "http://tempuri.org/ILoyaltyIntegration/GenerazioneBuono")
    @WebResult(name = "GenerazioneBuonoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerazioneBuono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerazioneBuono")
    @ResponseWrapper(localName = "GenerazioneBuonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerazioneBuonoResponse")
    public RisultatoGenerazioneBuono generazioneBuono(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "verificaCodice", targetNamespace = "http://tempuri.org/")
        VerificaCodice verificaCodice,
        @WebParam(name = "valoreRichiesto", targetNamespace = "http://tempuri.org/")
        String valoreRichiesto,
        @WebParam(name = "puntiRichiesti", targetNamespace = "http://tempuri.org/")
        Integer puntiRichiesti);

    /**
     * 
     * @param datiClient
     * @param codiceBuono
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoVerificaBuono
     */
    @WebMethod(operationName = "VerificaBuono", action = "http://tempuri.org/ILoyaltyIntegration/VerificaBuono")
    @WebResult(name = "VerificaBuonoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificaBuono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificaBuono")
    @ResponseWrapper(localName = "VerificaBuonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificaBuonoResponse")
    public RisultatoVerificaBuono verificaBuono(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "codiceBuono", targetNamespace = "http://tempuri.org/")
        String codiceBuono);

    /**
     * 
     * @param valutaSpesa
     * @param datiClient
     * @param codiceBuono
     * @param totaleSpesa
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoUtilizzoBuono
     */
    @WebMethod(operationName = "UtilizzaBuono", action = "http://tempuri.org/ILoyaltyIntegration/UtilizzaBuono")
    @WebResult(name = "UtilizzaBuonoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UtilizzaBuono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UtilizzaBuono")
    @ResponseWrapper(localName = "UtilizzaBuonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UtilizzaBuonoResponse")
    public RisultatoUtilizzoBuono utilizzaBuono(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient,
        @WebParam(name = "codiceBuono", targetNamespace = "http://tempuri.org/")
        String codiceBuono,
        @WebParam(name = "totaleSpesa", targetNamespace = "http://tempuri.org/")
        String totaleSpesa,
        @WebParam(name = "valutaSpesa", targetNamespace = "http://tempuri.org/")
        String valutaSpesa);

    /**
     * 
     * @param datiClient
     * @return
     *     returns org.datacontract.schemas._2004._07.expert_loyalty_ws.RisultatoTagliBuono
     */
    @WebMethod(operationName = "ElencaTagliBuono", action = "http://tempuri.org/ILoyaltyIntegration/ElencaTagliBuono")
    @WebResult(name = "ElencaTagliBuonoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ElencaTagliBuono", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ElencaTagliBuono")
    @ResponseWrapper(localName = "ElencaTagliBuonoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ElencaTagliBuonoResponse")
    public RisultatoTagliBuono elencaTagliBuono(
        @WebParam(name = "datiClient", targetNamespace = "http://tempuri.org/")
        DatiClient datiClient);

}
